version: '3.8'

services:
  app:
    container_name: rise_news
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    container_name: rise_news_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: J0hn@adep0ju
      POSTGRES_DB: rise_news
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: rise_news_redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
